

[Log]
Path = "logs/login.log"
Level = "debug"

[Websocket]
ListenHost = "0.0.0.0"
ListenPort = 3000
Multicore = true

[Router]
Address = "haomiao-yx.com:4000"


[Consul]
Address = "haomiao-yx.com:8500"

[Rpc]
ListenHost = "haomiao-yx.com"
ListenPort = 4001
