
[Log]
Path = "logs/msgpush.log"
Level = "debug"

[Rpc]
ListenHost = "haomiao-yx.com"
ListenPort = 4003

[Database]
Host = "haomiao-yx.com"
Port = 3306
User = "root"
Password = "my-secret-pw"
Database = "xiaogongqiu"


[Consul]
Address = "haomiao-yx.com:8500"

[Kafka]
Addresses = "haomiao-yx.com:9092"
MsgTopic = "im-msg-push"
MsgTopicGroup = "im-msg-push-group-1000"