[Rpc]
ListenHost = "haomiao-yx.com"
ListenPort = 4003

[Consul]
Address = "haomiao-yx.com:8500"

[Kafka]
Addresses = "haomiao-yx.com:9092"
MsgTopic = "im-msg-push"
MsgTopicGroup = "im-msg-push-group-1000"