

[Log]
Path = "logs/online.log"
Level = "debug"


[Rpc]
ListenHost = "haomiao-yx.com"
ListenPort = 4004

[Consul]
Address = "haomiao-yx.com:8500"

[Redis]
Addr = "haomiao-yx.com:6379"
Password = ""

[App]
#  在线用户超时
OnlineUserTimeOutSeconds = 11